version: '3.7'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  dental-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: dental-api
    expose:
      - '1337'
    ports:
      - '1337:1337'
    command: npm run dev